package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/gminetoma/go-auth/src/transport/cookies"
	"github.com/gminetoma/go-auth/src/transport/graphql/auth"
	"github.com/gminetoma/go-auth/src/transport/middleware"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*TokenPair, error) {
	pair, err := r.AuthService.Login(ctx, email, password)
	if err != nil {
		return nil, graphql.ErrorOnPath(ctx, err)
	}

	if w, ok := middleware.Writer(ctx); ok {
		cookies.SetAccessToken(w, pair.AccessToken, r.AccessTokenExpiry)
		cookies.SetRefreshToken(w, pair.RefreshToken, r.RefreshTokenExpiry)
	}

	return &TokenPair{
		AccessToken:  pair.AccessToken,
		RefreshToken: pair.RefreshToken,
	}, nil
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context, refreshToken *string) (*TokenPair, error) {
	token, err := auth.RefreshTokenFromContext(ctx, refreshToken)
	if err != nil {
		return nil, graphql.ErrorOnPath(ctx, err)
	}

	pair, err := r.AuthService.Refresh(ctx, token)
	if err != nil {
		return nil, graphql.ErrorOnPath(ctx, err)
	}

	if w, ok := middleware.Writer(ctx); ok {
		cookies.SetAccessToken(w, pair.AccessToken, r.AccessTokenExpiry)
		cookies.SetRefreshToken(w, pair.RefreshToken, r.RefreshTokenExpiry)
	}

	return &TokenPair{
		AccessToken:  pair.AccessToken,
		RefreshToken: pair.RefreshToken,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken *string) (bool, error) {
	token, err := auth.RefreshTokenFromContext(ctx, refreshToken)
	if err != nil {
		return false, err
	}

	if err := r.AuthService.Logout(ctx, token); err != nil {
		return false, err
	}

	if w, ok := middleware.Writer(ctx); ok {
		cookies.ClearAuth(w)
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (string, error) {
	ownerID, err := r.AuthService.Me(ctx)
	if err != nil {
		return "", graphql.ErrorOnPath(ctx, err)
	}

	return string(ownerID), nil
}
