// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Mutation struct {
}

type Query struct {
}

type TokenPair struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
