// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO
    users (id, created_at)
VALUES
    ($1, $2)
`

type CreateUserParams struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.CreatedAt)
	return err
}

const findUserByID = `-- name: FindUserByID :one
SELECT
    id, created_at
FROM
    users
WHERE
    id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
