// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package sqlc

import (
	"context"
	"time"
)

const createCredentials = `-- name: CreateCredentials :exec
INSERT INTO
    credentials (
        id,
        owner_id,
        email,
        password_hash,
        created_at,
        updated_at
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
`

type CreateCredentialsParams struct {
	ID           string
	OwnerID      string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateCredentials(ctx context.Context, arg CreateCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, createCredentials,
		arg.ID,
		arg.OwnerID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findCredentialsByEmail = `-- name: FindCredentialsByEmail :one
SELECT
    id, owner_id, email, password_hash, created_at, updated_at
FROM
    credentials
WHERE
    email = $1
`

func (q *Queries) FindCredentialsByEmail(ctx context.Context, email string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, findCredentialsByEmail, email)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
