// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO
    refresh_tokens (
        id,
        owner_id,
        token_hash,
        expires_at,
        created_at,
        revoked_at
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
`

type CreateRefreshTokenParams struct {
	ID        string
	OwnerID   string
	TokenHash []byte
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.OwnerID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	return err
}

const deleteRefreshTokenByToken = `-- name: DeleteRefreshTokenByToken :exec
DELETE FROM refresh_tokens
WHERE
    token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokenByToken, tokenHash)
	return err
}

const findRefreshTokenByToken = `-- name: FindRefreshTokenByToken :one
SELECT
    id, owner_id, token_hash, expires_at, revoked_at, created_at
FROM
    refresh_tokens
WHERE
    token_hash = $1
`

func (q *Queries) FindRefreshTokenByToken(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findRefreshTokenByToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :execrows
UPDATE refresh_tokens
SET
    revoked_at = $1
WHERE
    id = $2
`

type UpdateRefreshTokenParams struct {
	RevokedAt sql.NullTime
	ID        string
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRefreshToken, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
